### ISSUE TITLE
Not showing sbd price

### ISSUE THREAD

**Issue by sourovafrin** [cutemachine/SteemDesk#10]
Steemdesk is not showing sbd price

**Comment by cutemachine** [comment]
Thanks for reporting. Yes, I saw the error in the developer console:

`Sorry, problem retrieving price history in USD for symbol SBD.`

There seems to be a problem with the price feed from CryptoCompare. I will look into it.

**Comment by cutemachine** [comment]
Fixed in [#11](https://github.com/cutemachine/SteemDesk/pull/11).
Published to [https://www.steemdesk.com](https://www.steemdesk.com).
