### ISSUE TITLE
Icon/Wallpaper for SteemDesk

### ISSUE THREAD

**Issue by loydjayme25** [cutemachine/SteemDesk#2]
I do hope you like it sir, i am open for any suggestions.

**For the Icon**
![icon](https://user-images.githubusercontent.com/37318022/38763760-2d0089b8-3fd5-11e8-8ca1-ced30061646a.png)

**For the wallpaper**
![wallpaper](https://user-images.githubusercontent.com/37318022/38763762-35841ec4-3fd5-11e8-9fd0-fa0574cb00b3.png)

**Comment by cutemachine** [comment]
Thanks for being proactive and making a logo. But there is already a logo in the repo I'm quite happy with. Really appreciate your effort.

**Comment by loydjayme25** [comment]
Okay sir , is there a chance you can use mine ?

**Comment by cutemachine** [comment]
I will stick to the one we already have. But thanks again for your effort.
