### ISSUE TITLE
STEEM and SBD price show wrongly

### ISSUE THREAD

**Issue by Cha0s0000** [cutemachine/SteemDesk#8]
maybe the api error   
![default](https://user-images.githubusercontent.com/13085816/39416114-df9d7b5e-4c7c-11e8-893b-f68e0554bedb.png)

**Comment by cutemachine** [comment]
Thanks for reporting the error. I will close this issue as it is the same as [#10](https://github.com/cutemachine/SteemDesk/issues/10).
